name: food_scanner_app
description: A sophisticated Food Scanner App with professional UI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  provider: ^6.0.5
  mobile_scanner: ^6.0.7
  shared_preferences: ^2.5.2
  http: ^1.0.0
  
  # Premium UI Dependencies
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_bg.jpg
    - assets/images/logo.png
    - assets/images/home_bg.jpg

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

dependency_overrides:
  firebase_auth_platform_interface: ^7.2.0
